Disallow: *?
Disallow: /m/
Disallow: /thank-you/
Disallow: /politica/
Disallow: /status/
Disallow: /?text*
#close
Disallow: */#marka-*/akkumulyator
Disallow: */#marka-*/cherniy-ekran
Disallow: */#marka-*/chistka-noutbuka
Disallow: */#marka-*/chistka-plansheta
Disallow: */#marka-*/chistka-telefona
Disallow: */#marka-*/deformatsiya-korpusa
Disallow: */#marka-*/deformatsiya-kryshki
Disallow: */#marka-*/diagnostika
Disallow: */#marka-*/dinamik
Disallow: */#marka-*/displey
Disallow: */#marka-*/gps
Disallow: */#marka-*/hdmi
Disallow: */#marka-*/kamera
Disallow: */#marka-*/klaviatura
Disallow: */#marka-*/knopka-vklyucheniya
Disallow: */#marka-*/korpus
Disallow: */#marka-*/kryshka
Disallow: */#marka-*/kuler
Disallow: */#marka-*/materinskaya-plata
Disallow: */#marka-*/matritsa
Disallow: */#marka-*/mikrofon
Disallow: */#marka-*/multikontroller
Disallow: */#marka-*/nastroyka-bios
Disallow: */#marka-*/nastroyka-windows
Disallow: */#marka-*/ne-gorit-ekran
Disallow: */#marka-*/ne-rabotaet-dinamik
Disallow: */#marka-*/ne-rabotaet-gps
Disallow: */#marka-*/ne-rabotaet-hdmi
Disallow: */#marka-*/ne-rabotaet-kamera
Disallow: */#marka-*/ne-rabotaet-klaviatura
Disallow: */#marka-*/ne-rabotaet-knopka
Disallow: */#marka-*/ne-rabotaet-mikrofon
Disallow: */#marka-*/ne-rabotaet-tachpad
Disallow: */#marka-*/ne-rabotaet-tachskrin
Disallow: */#marka-*/ne-rabotaet-usb
Disallow: */#marka-*/ne-rabotaet-vibro
Disallow: */#marka-*/ne-rabotaet-wifi
Disallow: */#marka-*/net-zvuka
Disallow: */#marka-*/ne-vidit-disk
Disallow: */#marka-*/ne-vidit-sim
Disallow: */#marka-*/ne-vkluchaetsya
Disallow: */#marka-*/ne-zagruzhaetsya
Disallow: */#marka-*/ne-zaryazhaetsya
Disallow: */#marka-*/operativnaya-pamyat
Disallow: */#marka-*/peregrevaetsya
Disallow: */#marka-*/perezagruzhaetsya
Disallow: */#marka-*/razborka-noutbuka
Disallow: */#marka-*/razborka-plansheta
Disallow: */#marka-*/razborka-telefona
Disallow: */#marka-*/razryazhaetsya
Disallow: */#marka-*/razyom-pitaniya
Disallow: */#marka-*/remont-severnogo-mosta
Disallow: */#marka-*/remont-tsepi-pitaniya
Disallow: */#marka-*/seveniy-most
Disallow: */#marka-*/shleyf
Disallow: */#marka-*/shleyf-matritsy
Disallow: */#marka-*/shumit
Disallow: */#marka-*/sim-holder
Disallow: */#marka-*/siniy-ekran
Disallow: */#marka-*/tachpad
Disallow: */#marka-*/usb
Disallow: */#marka-*/ustanovka-drayverov
Disallow: */#marka-*/vibro
Disallow: */#marka-*/videokarta
Disallow: */#marka-*/vykluchaetsya
Disallow: */#marka-*/wifi
Disallow: */#marka-*/yuzhniy-most
Disallow: */#marka-*/zamena-batarei
Disallow: */#marka-*/zamena-derzhatelya-sim
Disallow: */#marka-*/zamena-dinamika
Disallow: */#marka-*/zamena-gnezda-pitaniya
Disallow: */#marka-*/zamena-hdmi
Disallow: */#marka-*/zamena-klaviatury
Disallow: */#marka-*/zamena-knopki-vklyucheniya
Disallow: */#marka-*/zamena-kulera
Disallow: */#marka-*/zamena-materinskoy-platy
Disallow: */#marka-*/zamena-matritsy
Disallow: */#marka-*/zamena-mikrofona
Disallow: */#marka-*/zamena-multikontrollera
Disallow: */#marka-*/zamena-pamyati
Disallow: */#marka-*/zamena-shleyfa
Disallow: */#marka-*/zamena-shleyfa-matritsy
Disallow: */#marka-*/zamena-tachpad
Disallow: */#marka-*/zamena-usb
Disallow: */#marka-*/zamena-vibro
Disallow: */#marka-*/zamena-videokarty
Disallow: */#marka-*/zamena-wifi
Disallow: */#marka-*/zamena-zadney-kryshki
Disallow: */#marka-*/zamena-zaryadnogo-ustroystva
Disallow: */#marka-*/zamena-zhestkogo-diska
Disallow: */#marka-*/zamena-zvukovoy-karty
Disallow: */#marka-*/zaryadnoe-ustroystvo
Disallow: */#marka-*/zhestkiy-disk
Disallow: */#marka-*/zvukovaya-karta
Disallow: */#marka-*/polosy-na-ekrane
Disallow: */#marka-*/razbit-ekran
Disallow: */#marka-*/remont-yuzhnogo-mosta
Disallow: */#marka-*/zamena-displeya
Disallow: */#marka-*/zamena-gps
Disallow: */#marka-*/zamena-kamery
Disallow: */#marka-*/zamena-korpusa
