Allow: *_#marka/*$
Disallow: /?
Disallow: /emarket/addToCompare
Disallow: /emarket/basket
Disallow: /go_out.php
Disallow: /images
Disallow: /images/lizing
Disallow: /images/ntc
Disallow: /files
Disallow: /users
Disallow: /admin
Disallow: /search
Disallow: /install-temp
Disallow: /install-static
Disallow: /install-libs
#close
Disallow: *_#marka/*/akkumulyator
Disallow: *_#marka/*/cherniy_ekran
Disallow: *_#marka/*/chistka_noutbuka
Disallow: *_#marka/*/chistka_plansheta
Disallow: *_#marka/*/chistka_telefona
Disallow: *_#marka/*/deformatsiya_korpusa
Disallow: *_#marka/*/deformatsiya_kryshki
Disallow: *_#marka/*/diagnostika
Disallow: *_#marka/*/dinamik
Disallow: *_#marka/*/displey
Disallow: *_#marka/*/gps
Disallow: *_#marka/*/hdmi
Disallow: *_#marka/*/kamera
Disallow: *_#marka/*/klaviatura
Disallow: *_#marka/*/knopka_vklyucheniya
Disallow: *_#marka/*/korpus
Disallow: *_#marka/*/kryshka
Disallow: *_#marka/*/kuler
Disallow: *_#marka/*/materinskaya_plata
Disallow: *_#marka/*/matritsa
Disallow: *_#marka/*/mikrofon
Disallow: *_#marka/*/multikontroller
Disallow: *_#marka/*/nastroyka_bios
Disallow: *_#marka/*/nastroyka_windows
Disallow: *_#marka/*/ne_gorit_ekran
Disallow: *_#marka/*/ne_rabotaet_dinamik
Disallow: *_#marka/*/ne_rabotaet_gps
Disallow: *_#marka/*/ne_rabotaet_hdmi
Disallow: *_#marka/*/ne_rabotaet_kamera
Disallow: *_#marka/*/ne_rabotaet_klaviatura
Disallow: *_#marka/*/ne_rabotaet_knopka
Disallow: *_#marka/*/ne_rabotaet_mikrofon
Disallow: *_#marka/*/ne_rabotaet_tachpad
Disallow: *_#marka/*/ne_rabotaet_tachskrin
Disallow: *_#marka/*/ne_rabotaet_usb
Disallow: *_#marka/*/ne_rabotaet_vibro
Disallow: *_#marka/*/ne_rabotaet_wifi
Disallow: *_#marka/*/net_zvuka
Disallow: *_#marka/*/ne_vidit_disk
Disallow: *_#marka/*/ne_vidit_sim
Disallow: *_#marka/*/ne_vkluchaetsya
Disallow: *_#marka/*/ne_zagruzhaetsya
Disallow: *_#marka/*/ne_zaryazhaetsya
Disallow: *_#marka/*/operativnaya_pamyat
Disallow: *_#marka/*/peregrevaetsya
Disallow: *_#marka/*/perezagruzhaetsya
Disallow: *_#marka/*/razborka_noutbuka
Disallow: *_#marka/*/razborka_plansheta
Disallow: *_#marka/*/razborka_telefona
Disallow: *_#marka/*/razryazhaetsya
Disallow: *_#marka/*/razyom_pitaniya
Disallow: *_#marka/*/remont_severnogo_mosta
Disallow: *_#marka/*/remont_tsepi_pitaniya
Disallow: *_#marka/*/remont_yuzhnogo_mosta
Disallow: *_#marka/*/seveniy_most
Disallow: *_#marka/*/shleyf
Disallow: *_#marka/*/shleyf_matritsy
Disallow: *_#marka/*/shumit
Disallow: *_#marka/*/sim_holder
Disallow: *_#marka/*/siniy_ekran
Disallow: *_#marka/*/tachpad
Disallow: *_#marka/*/usb
Disallow: *_#marka/*/ustanovka_drayverov
Disallow: *_#marka/*/vibro
Disallow: *_#marka/*/videokarta
Disallow: *_#marka/*/vykluchaetsya
Disallow: *_#marka/*/wifi
Disallow: *_#marka/*/yuzhniy_most
Disallow: *_#marka/*/zamena_batarei
Disallow: *_#marka/*/zamena_derzhatelya_sim
Disallow: *_#marka/*/zamena_dinamika
Disallow: *_#marka/*/zamena_displeya
Disallow: *_#marka/*/zamena_gnezda_pitaniya
Disallow: *_#marka/*/zamena_gps
Disallow: *_#marka/*/zamena_hdmi
Disallow: *_#marka/*/zamena_kamery
Disallow: *_#marka/*/zamena_klaviatury
Disallow: *_#marka/*/zamena_knopki_vklyucheniya
Disallow: *_#marka/*/zamena_korpusa
Disallow: *_#marka/*/zamena_kulera
Disallow: *_#marka/*/zamena_materinskoy_platy
Disallow: *_#marka/*/zamena_matritsy
Disallow: *_#marka/*/zamena_mikrofona
Disallow: *_#marka/*/zamena_multikontrollera
Disallow: *_#marka/*/zamena_pamyati
Disallow: *_#marka/*/zamena_shleyfa
Disallow: *_#marka/*/zamena_shleyfa_matritsy
Disallow: *_#marka/*/zamena_tachpad
Disallow: *_#marka/*/zamena_usb
Disallow: *_#marka/*/zamena_vibro
Disallow: *_#marka/*/zamena_videokarty
Disallow: *_#marka/*/zamena_wifi
Disallow: *_#marka/*/zamena_zadney_kryshki
Disallow: *_#marka/*/zamena_zaryadnogo_ustroystva
Disallow: *_#marka/*/zamena_zhestkogo_diska
Disallow: *_#marka/*/zamena_zvukovoy_karty
Disallow: *_#marka/*/zaryadnoe_ustroystvo
Disallow: *_#marka/*/zhestkiy_disk
Disallow: *_#marka/*/zvukovaya_karta
Disallow: *_#marka/*/polosy_na_ekrane
Disallow: *_#marka/*/razbit_ekran