<?php

use framework\pdo;
use framework\rand_it;
use framework\tools;

if (!function_exists('get_populars')) {
    function get_populars()
    {
        $populars = [

            "xiaomi" => [
                "f" => [
                    "Xiaomi Mi4i",
                    "Xiaomi Redmi Note 4",
                    "Xiaomi Redmi Note 3 Pro SE",
                    "Xiaomi Mi Max",
                    "Xiaomi Mi Note",
                    "Xiaomi Redmi 3S",
                    "Xiaomi Redmi Note 4G",
                    "Xiaomi Redmi Pro",
                    "Xiaomi Redmi Note 2",
                    "Xiaomi Redmi Note 3/pro",
                    "Xiaomi Mi Mix 2",
                    "Xiaomi Mi5S",
                    "Xiaomi mi4s",
                    "Xiaomi Mi5",
                    "Xiaomi Mi Note 2",
                    "Xiaomi Mi6",
                    "Xiaomi Mi Mix 2 S",
                    "Xiaomi Redmi 4X",
                    "Xiaomi Redmi 5 Plus",
                    "Xiaomi Redmi 4",
                    "Xiaomi Mi Mix",
                    "Xiaomi Redmi Note 5A",
                    "Xiaomi Redmi 5",
                    "Xiaomi Redmi 4A",
                    "Xiaomi Redmi 4 Prime",
                    "Xiaomi Mi5C",
                    "Xiaomi Mi5X",
                    "Xiaomi redmi 3x",
                    "Xiaomi Mi Note 3",
                    "Xiaomi Redmi 5A",
                    "Xiaomi Redmi Note 4X",
                    "Xiaomi Redmi Note 5A Prime",
                    "Xiaomi mi4c",
                    "Xiaomi Mi A1",
                    "Xiaomi mi max2",
                    "Xiaomi mi5s plus",
                    "Xiaomi mi4",
                ],
                "p" => [
                    "Xiaomi mipad",
                    "Xiaomi mipad 2",
                    "Xiaomi mipad 3",
                ],
                "n" => [
                    "Xiaomi mi gaming laptop",
                    "Xiaomi mi notebook pro",
                    "Xiaomi mi notebook air 12.5",
                    "Xiaomi mi notebook air 13.3",
                ],
            ],
            "acer" => [
                "n" => [
                    "Acer Aspire A515 51G",
                    "Acer Aspire A715 71G",
                    "Acer Aspire A715 71G 50Pl",
                    "Acer Aspire A715 71G 51J1",
                    "Acer Aspire A715 71G 523H",
                    "Acer Aspire A715 71G 52Jf",
                    "Acer Aspire A715 71G 71S3",
                    "Acer Aspire 7 A717 71G",
                    "Acer Aspire A717 71G 50Sy",
                    "Acer Aspire V3 372",
                    "Acer Aspire V5 591G 50Rf",
                    "Acer Aspire Vn7 792G 54Ld",
                    "Acer Aspire Vx5 591G",
                    "Acer Aspire Vx5 591G 5544",
                    "Acer Aspire Vx5 591G 58Ke",
                    "Acer Vx5 591G 59Hf",
                    "Acer Vx5 591G 72T2",
                    "Acer Vx5 591G 75Ay",
                    "Acer Vx5 591G 76X9",
                    "Acer Vx5 591G 79M2",
                    "Acer E5 523 6973",
                    "Acer E5 532 C5Sz",
                    "Acer E5 553G",
                    "Acer E5 553G 12Kq",
                    "Acer E5 575G",
                    "Acer E5 575G 34Ps",
                    "Acer E5 575G 35Ra",
                    "Acer E5 575G 51Jy",
                    "Acer E5 575G 53V2",
                    "Acer E5 575G 53S6",
                    "Acer E5 575G 55J7",
                    "Acer E5 575G 56C3",
                    "Acer E5 575G 57Kj",
                    "Acer E5 575G 57Pb",
                    "Acer E5 575G 57X6",
                    "Acer E5 575G 71H4",
                    "Acer E5 772 34B4",
                    "Acer E5 772G 38Uy",
                    "Acer E5 772G 59Sx",
                    "Acer E5 774G 5154",
                    "Acer Es1 523",
                    "Acer Es1 523 45Lc",
                    "Acer Es1 523 80Jf",
                    "Acer Es1 523 84Q5",
                    "Acer Es1 523 886K",
                    "Acer Es1 533 C972",
                    "Acer Es1 731 C50Q",
                    "Acer Es1 732 P3Zg",
                    "Acer S5 371",
                    "Acer S5 371 70Af",
                    "Acer S5 371T 5409",
                    "Acer F5 571G P8Pj",
                    "Acer F5 573G 509X",
                    "Acer F5 573G 71S6",
                    "Acer F5 573G 79Zk",
                    "Acer An515 31 584G",
                    "Acer An515 51",
                    "Acer Predator 15",
                    "Acer Predator 17",
                    "Acer Predator 17 G5 793",
                    "Acer Predator 17 G9 793",
                    "Acer Helios 300 G3 572",
                    "Acer Helios 300 G3 572 57F0",
                    "Acer Helios 300 Ph317 51",
                    "Acer Swift 1",
                    "Acer Swift 1 Sf113 31",
                    "Acer Swift 3 Sf314 51",
                    "Acer Swift 3 Sf314 52",
                    "Acer Swift 3 Sf314 52G",
                    "Acer Swift 3 Sf314 52G 87De",
                    "Acer Swift 3 Sf315 51G 50Se",
                    "Acer Swift 5",
                    "Acer Swift 7",
                    "Acer Spin 1 Sp111 32N",
                    "Acer Spin 1 Sp111 32N P25R",
                    "Acer Spin 5",
                    "Acer Spin 7",
                    "Acer B117 M C2Se",
                    "Acer Travelmate P2",
                    "Acer P2 P259Mg",
                    "Acer P2 P259 Mg 39Ns",
                    "Acer P238 M P718",
                    "Acer P238 M P96L",
                    "Acer Ex2511G",
                    "Acer Ex2511G 31Jn",
                    "Acer Ex2511G 35D4",
                    "Acer Ex2511G 56Da",
                    "Acer Ex2511G P5F1",
                    "Acer Ex2519",
                    "Acer Ex2519 P0Bd",
                    "Acer Ex2519 P0Bt",
                    "Acer Ex2519 P5Pg",
                    "Acer Ex2519 P79W",
                    "Acer Ex2519 C08K",
                    "Acer Ex2519 C298",
                    "Acer Ex2519 C33F",
                    "Acer Ex2520G",
                    "Acer Ex2520G 537T",
                    "Acer Ex2520G P0G5",
                    "Acer Ex2520G P2Jg",
                    "Acer Ex2520G P49C",
                    "Acer Ex2530 36Nw",
                    "Acer Ex2530 C1Fj",
                    "Acer Ex2540",
                    "Acer Ex2540 3075",
                    "Acer Ex2540 30P4",
                    "Acer Ex2540 30R0",
                    "Acer Ex2540 34Yr",
                    "Acer Ex2540 36H1",
                    "Acer Ex2540 37En",
                    "Acer Ex2540 37Wm",
                    "Acer Ex2540 55Bu",
                    "Acer Ex2540 561V",
                    "Acer Ex2540 56Z8",
                    "Acer Aspire S7-393",
                    "Acer Aspire 8943",
                ],
                "f" => [
                    "Acer Liquid Z410",
                    "Acer Liquid Jade Z",
                    "Acer Liquid Z525 Duo",
                ],
                "p" => [
                    "Acer Iconia Tab A3-A40",
                ],
            ],
            "alcatel" => [
                "f" => [
                    "Alcatel Idol 3",
                    "Alcatel Shine Lite",
                    "Alcatel OT355D",
                    "Alcatel OT710",
                    "Alcatel 7044Y",
                    "Alcatel 6032x",
                    "Alcatel OT233",
                    "Alcatel 318D",
                    "Alcatel 8000D",
                    "Alcatel OneTouch 208",
                    "Alcatel One Touch POP 4",
                    "Alcatel OneTouch 918D",
                    "Alcatel OT217D",
                    "Alcatel OneTouch POP",
                    "Alcatel OneTouch POP 4 Plus",
                    "Alcatel ONE TOUCH POP STAR",
                    "Alcatel U3 3G Dual sim",
                    "Alcatel OneTouch Pixi 3",
                    "Alcatel 7070",
                    "Alcatel Pop Star 4G",
                    "Alcatel A3 PLUS 3G",
                    "Alcatel One Touch POP 3",
                    "Alcatel TOUCH PIXI 4",
                    "Alcatel OneTouch PIXI 4",
                    "Alcatel IDOL 4S",
                    "Alcatel A5",
                    "Alcatel PIXI 4",
                    "Alcatel A3",
                    "Alcatel 5",
                    "Alcatel A7",
                    "Alcatel 3C",
                    "Alcatel A3 XL",
                    "Alcatel U5 HD",
                    "Alcatel A5 LED",
                    "Alcatel IDOL 4",
                    "Alcatel OneTouch 1035D",
                    "Alcatel U5 4G",
                    "Alcatel OneTouch 1016D",
                    "Alcatel OneTouch 1020D",
                    "Alcatel OneTouch 2007D",
                    "Alcatel 5099D",
                    "Alcatel OneTouch 1054D",
                    "Alcatel OneTouch 4047D",
                    "Alcatel OneTouch 6058D",
                    "Alcatel OneTouch 2008G",
                    "Alcatel OneTouch 2051D",
                ],
            ],
            "apple" => [
                "n" => [
                    "Apple MACBOOK Air 11",
                    "Apple MacBook 12 Retina",
                    "Apple MacBook Air 13",
                    "Apple MacBook PRO 13",
                    "Apple MacBook Pro",
                    "Apple macbook pro 15",
                    "Apple macbook pro 17",
                    "Apple MacBook Pro 13 Retina",
                ],
                "p" => [
                    "Apple ipad 2",
                    "Apple ipad 3/4",
                    "Apple ipad mini",
                    "Apple ipad mini 2",
                    "Apple ipad mini 3",
                    "Apple ipad mini 4",
                    "Apple ipad air",
                    "Apple ipad air 2",
                    "Apple ipad 5(2017)",
                    "Apple ipad 6(2018)",
                    "Apple ipad pro 9.7",
                    "Apple ipad pro 10.5",
                    "Apple ipad pro 12.9",
                ],
                "f" => [
                    "Apple iphone 3g",
                    "Apple iphone 3gs",
                    "Apple iphone 4",
                    "Apple iphone 4s",
                    "Apple iphone 5/5c",
                    "Apple iphone 5s/se",
                    "Apple iphone 6",
                    "Apple iphone 6 plus",
                    "Apple iphone 6s",
                    "Apple iphone 6s plus",
                    "Apple iphone 7",
                    "Apple iphone 7 plus",
                    "Apple iphone 8",
                    "Apple iphone 8 plus",
                    "Apple iphone X",
                ],
            ],
            "asus" => [
                "n" => [
                    "Asus f50",
                    "Asus f6",
                    "Asus k95vj",
                    "Asus k53s",
                    "Asus k55",
                    "Asus f3j",
                    "Asus f3k",
                    "Asus k750j",
                    "Asus k50",
                    "Asus f553m",
                    "Asus g60",
                    "Asus eee pc 1015b",
                    "Asus k52n",
                    "Asus k53",
                    "Asus k56cb",
                    "Asus f9",
                    "Asus k52",
                    "Asus f3",
                    "Asus f5",
                    "Asus f8",
                    "Asus x200m",
                    "Asus VivoBook Pro 15 N580VD",
                    "Asus X552CL",
                    "Asus N56VZ",
                ],
                "p" => [
                    "Asus Zenpad Z581Kl",
                    "Asus Zenpad z380",
                    "Asus t100",
                    "Asus MemoPad Me173X",
                    "Asus MemoPad Me172V",
                    "Asus me102",
                    "Asus Zenpad 10",
                    "Asus t305",
                    "Asus t102",
                    "Asus t103",
                    "Asus z170",
                    "Asus z300",
                ],
                "f" => [
                    "Asus ZenFone C",
                    "Asus ZenFone 3s Max",
                    "Asus Zenfone 5 LTE",
                    "Asus ZenFone 3 Zoom",
                    "Asus ZenFone 2",
                    "Asus ZenFone 4 Selfie Pro",
                    "Asus Zenfone 4 Max Plus",
                    "Asus ZenFone Zoom",
                    "Asus ZenFone 2 Laser",
                    "Asus ZenFone 2 Laser",
                    "Asus ZenFone Selfie",
                    "Asus ZenFone 2 Laser",
                    "Asus ZenFone 4 Pro",
                    "Asus ZenFone 3 Ultra",
                    "Asus ZenFone 3 Max",
                    "Asus ZenFone AR",
                    "Asus ZenFone 3 Deluxe",
                    "Asus ZenFone 3",
                    "Asus Zenfone Max",
                    "Asus ZenFone 5",
                    "Asus ZenFone Max Plus",
                    "Asus ZenFone 4 Max",
                    "Asus ZenFone 5 Lite",
                    "Asus ZenFone Live",
                    "Asus ZenFone 4 Selfie",
                    "Asus ZenFone 4 Live",
                    "Asus ZenFone 4",
                    "Asus ZenFone 3 Laser",
                    "Asus ZenFone Go",
                ],
            ],
            "dell" => [
                "n" => [
                    "Dell inspiron 3521",
                    "Dell vostro a860",
                    "Dell latitude d610",
                    "Dell inspiron 1520",
                    "Dell inspiron 3520",
                    "Dell vostro 3550",
                    "Dell xps m1330 m1330",
                    "Dell inspiron 1318",
                    "Dell inspiron 15r n5110",
                    "Dell inspiron 5555",
                    "Dell inspiron xps",
                    "Dell inspiron 1501",
                    "Dell inspiron 5558",
                    "Dell inspiron 600m",
                    "Dell inspiron m5040",
                    "Dell latitude d400",
                    "Dell vostro 1000",
                    "Dell inspiron 15 5567",
                    "Dell inspiron 1521",
                    "Dell inspiron 1720",
                ],
                "p" => [
                    "Dell Latitude 7285-8701",
                    "Dell Latitude 7285-8718",
                    "Dell Latitude 7285-8725",
                ],
            ],
            "fly" => [
                "f" => [
                    "Fly FF182",
                    "Fly Cirrus 3",
                    "Fly Cirrus 4",
                    "Fly Stratus 6",
                    "Fly Nimbus 14",
                    "Fly Nimbus 9",
                    "Fly Nimbus 7",
                    "Fly Cirrus 16",
                    "Fly FF178",
                    "Fly Ezzy7",
                    "Fly TS112",
                    "Fly Nimbus 8",
                    "Fly Cirrus 2",
                    "Fly Cirrus 6",
                    "Fly Trendy 3",
                    "Fly TS113",
                    "Fly Stratus 8",
                    "Fly Nimbus 16",
                    "Fly Memory Plus",
                    "Fly DS111",
                    "Fly ST100",
                    "Fly TS91",
                    "Fly Cumulus 1",
                    "Fly Nimbus 4",
                    "Fly Cirrus 8",
                    "Fly B400",
                    "Fly Ezzy 9",
                    "Fly FF248",
                    "Fly Cirrus 12",
                    "Fly FF281",
                    "Fly Nimbus 10",
                    "Fly Power Plus 1",
                    "Fly FS521",
                    "Fly FF179",
                    "Fly TS2050",
                    "Fly Stratus 5",
                    "Fly Horizon",
                    "Fly ERA Nano 10",
                    "Fly DS",
                    "Fly FF181",
                    "Fly E105",
                    "Fly FF242",
                    "Fly MC110",
                    "Fly FF249",
                    "Fly FF177",
                    "Fly Cirrus 7",
                    "Fly Stratus 4",
                    "Fly Genius",
                    "Fly Trend",
                    "Fly DS110",
                    "Fly TS90",
                    "Fly E157",
                    "Fly IQ4505",
                    "Fly E130",
                    "Fly FS458",
                    "Fly Сhamp",
                    "Fly Cirrus 13",
                    "Fly Cirrus 14",
                    "Fly Ezzy 7+",
                    "Fly Cirrus 11",
                    "Fly FF247",
                    "Fly Power Plus FHD",
                    "Fly FF180",
                    "Fly Nimbus 17",
                    "Fly FF244",
                    "Fly FS520",
                    "Fly Power Plus XXL",
                    "Fly Power Plus 2",
                    "Fly Knockout",
                    "Fly FF245",
                    "Fly FF241",
                    "Fly Ezzy 5",
                    "Fly Tornado Slim",
                    "Fly DS103D",
                    "Fly 5S",
                    "Fly Nimbus 15",
                    "Fly E210",
                ],
            ],
            "hp" => [
                "n" => [
                    "HP probook 4525s",
                    "HP nc2400",
                    "HP probook 4520s",
                    "HP probook 4535s",
                    "HP 255 g4",
                    "HP pavilion g6-1000",
                    "HP probook 450 g3",
                    "HP 250 g3",
                    "HP 250 g4",
                    "HP 6730s",
                    "HP 8510p",
                    "HP elitebook 8540w",
                    "HP envy dv6-7200",
                    "HP pavilion dv3500",
                    "HP pavilion dv6-3000",
                    "HP pavilion dv9500",
                    "HP elitebook 850 g3",
                    "HP ProBook 470 G5",
                    "HP Pavilion 17( HP 17-E157)",
                ],
                "p" => [
                    "HP Pavilion x2 10-k001nr",
                    "HP Pavilion x2 10-p001ur",
                    "HP ElitePad 900 32Gb 3G",
                    "HP X2 Detachable 10-p005ur",
                ],
            ],
            "htc" => [
                "f" => [
                    "HTC One mini",
                    "HTC Desire 816",
                    "HTC One mini 2",
                    "HTC x10",
                    "HTC Butterfly S",
                    "HTC One M9",
                    "HTC One E9s Dual",
                    "HTC Desire 526g",
                    "HTC U11",
                    "HTC 10 Lifestyle",
                    "HTC 10 Evo",
                    "HTC Desire 628",
                    "HTC One M8",
                    "HTC One M7",
                    "HTC One A9s",
                    "HTC Desire 626",
                    "HTC Desire 828",
                    "HTC One E9 Plus E9PW",
                    "HTC One A9",
                    "HTC Desire 530",
                    "HTC Desire 820",
                    "HTC Desire 601",
                    "HTC One V",
                    "HTC Desire X",
                    "HTC Wildfire",
                ],
                "p" => [
                    "HTC Flyer Wi-Fi + 3G",
                    "HTC Nexus 9 LTE",
                ],
            ],
            "huawei" => [
                "p" => [
                    "Huawei Mediapad M2-801",
                    "Huawei Mediapad T1-701",
                    "Huawei Mediapad T1-821",
                    "Huawei Mediapad M3 lite 10.0",
                    "Huawei Mediapad T3 7.0",
                    "Huawei Mediapad T2 7.0",
                    "Huawei Mediapad T2 PRO",
                    "Huawei Mediapad T3 8.4",
                    "Huawei Mediapad X1",
                    "Huawei Mediapad S10 101",
                    "Huawei Mediapad S8-301",
                ],
                "f" => [
                    "Huawei Honor 8",
                    "Huawei Ascend Y3 2017",
                    "Huawei Ascend P9 lite",
                    "Huawei Ascend P8",
                    "Huawei Ascend P9",
                    "Huawei Ascend P10",
                    "Huawei P8 lite",
                    "Huawei Nova 2",
                    "Huawei Honor 8 lite",
                    "Huawei Mate 9 Porsche",
                    "Huawei Mate 10",
                    "Huawei P Smart",
                    "Huawei Honor 7x",
                    "Huawei Honor View 10",
                    "Huawei Honor 9",
                    "Huawei Mate 10 Pro",
                    "Huawei Mate 9",
                    "Huawei Mate 8",
                    "Huawei Ascend Y7",
                    "Huawei Mate 9 Pro",
                    "Huawei Ascend G7",
                    "Huawei Ascend Y5 2017",
                    "Huawei Nova 2 Plus",
                    "Huawei Ascend Y6",
                    "Huawei Honor 4c",
                ],
            ],
            "lenovo" => [
                "n" => [
                    "Lenovo thinkpad x200",
                    "Lenovo v580c",
                    "Lenovo thinkpad x240",
                    "Lenovo v570",
                    "Lenovo thinkpad t431s",
                    "Lenovo thinkpad t460s",
                    "Lenovo thinkpad t540p",
                    "Lenovo thinkpad x1",
                    "Lenovo thinkpad x1 carbon",
                    "Lenovo thinkpad edge 14",
                    "Lenovo thinkpad sl400",
                    "Lenovo thinkpad t440",
                    "Lenovo thinkpad t520",
                    "Lenovo v310",
                    "Lenovo yoga 2 13",
                    "Lenovo z50",
                    "Lenovo z50 75",
                    "Lenovo thinkpad 11e",
                    "Lenovo thinkpad 11e chromebook",
                    "Lenovo thinkpad 13",
                    "Lenovo ThinkPad T450",
                ],
                "p" => [
                    "Lenovo IdeaTab A7600 16Gb 3G",
                    "Lenovo Tablet S8 S8-50F",
                    "Lenovo Miix 320 10",
                    "Lenovo Tab 2 A7-30",
                    "Lenovo Tab 2 A8-50",
                    "Lenovo Yoga 3 Tablet 8",
                    "Lenovo Tab 4 TB-7504X",
                    "Lenovo Tab 3 Essential",
                    "Lenovo IdeaPad Miix 700",
                    "Lenovo Tab 3 TB3-850",
                    "Lenovo Yoga Book YB1-X91L",
                    "Lenovo Tab 4 TB-X704L",
                    "Lenovo Tab 4 TB-X304L",
                    "Lenovo Yoga Tablet 10 b8000",
                    "Lenovo IdeaTab A2107A",
                    "Lenovo ThinkPad Helix i5",
                    "Lenovo IdeaTab A3000",
                    "Lenovo IdeaTab A5500",
                    "Lenovo IdeaTab A3500",
                ],
                "f" => [
                    "Lenovo P70",
                    "Lenovo A5000",
                    "Lenovo A536",
                    "Lenovo P780",
                    "Lenovo A1000",
                    "Lenovo S850",
                    "Lenovo Vibe Shot",
                    "Lenovo S60",
                    "Lenovo A6010",
                    "Lenovo A2010",
                    "Lenovo S820",
                    "Lenovo A319",
                    "Lenovo K3",
                    "Lenovo S660",
                    "Lenovo K3 Note",
                    "Lenovo Vibe X2",
                    "Lenovo A328",
                    "Lenovo A859",
                    "Lenovo P2",
                    "Lenovo S860",
                ],
            ],
            "lg" => [
                "f" => [
                    "LG G Flex 2",
                    "LG G4 H818",
                    "LG KG195",
                    "LG G Pro 2 D838",
                    "LG Spirit H422",
                    "LG G3 Dual-LTE D856",
                    "LG Leon LTE H340",
                    "LG G3 Dual D858",
                    "LG G Pro Lite D684",
                    "LG X Power 2 M320",
                    "LG G360",
                    "LG Stylus 2 K520",
                    "LG Nexus 5 D821",
                    "LG Leon H324",
                    "LG V20",
                    "LG Optimus True HD P936",
                    "LG X Fast",
                    "LG L Fino D295",
                    "LG Spirit H440Y",
                    "LG Nexus 5X H791",
                    "LG G2 Mini D618",
                    "LG Optimus L5 E612",
                    "LG L Bello D335",
                    "LG G4 H815",
                    "LG G2 D802",
                    "LG G4s H734",
                    "LG G Pro Lite Dual D686",
                    "LG G4 Stylus 4G H630",
                    "LG K4 K120E",
                    "LG G Flex D958",
                    "LG Optimus G Pro E988",
                    "LG X cam K580DS",
                    "LG G4s H736",
                    "LG K7 X210DS",
                    "LG G3s D724",
                    "LG K3 K100DS",
                    "LG G4c H522y",
                    "LG V30",
                    "LG K8 K350E",
                    "LG K500DS",
                    "LG L Bello D331",
                    "LG Optimus F5 4G LTE P875",
                    "LG G5 H860",
                    "LG G Pro E988",
                    "LG G3 Cat. 6",
                    "LG Max X155",
                    "LG G3 D855",
                    "LG Optimus 4X HD P880",
                    "LG G3 Stylus D690",
                    "LG G3S D722",
                    "LG K10 K430N",
                    "LG K10 K410",
                    "LG Magna",
                    "LG Class",
                    "LG K5",
                    "LG X Style",
                    "LG Stylus 3",
                    "LG G6+",
                    "LG K10",
                    "LG K8",
                    "LG Q6",
                    "LG V30+",
                ],
            ],
            "meizu" => [
                "f" => [
                    "Meizu M3 Max",
                    "Meizu MX2",
                    "Meizu M9",
                    "Meizu U20",
                    "Meizu MX3",
                    "Meizu MX4 Pro",
                    "Meizu Meilan X",
                    "Meizu M2 Note",
                    "Meizu U10",
                    "Meizu E2",
                    "Meizu M1 Note",
                    "Meizu MX4",
                    "Meizu M3",
                    "Meizu MX5",
                    "Meizu MX4 Ubuntu",
                    "Meizu A5",
                    "Meizu M5c",
                    "Meizu M6",
                    "Meizu Metal",
                    "Meizu mx6",
                    "Meizu M3 Note",
                    "Meizu M3E",
                    "Meizu Pro 6",
                    "Meizu M5 Note",
                    "Meizu M3s",
                    "Meizu M6 Note",
                    "Meizu Pro 7",
                    "Meizu Pro 6s",
                    "Meizu PRO 5",
                    "Meizu M5s",
                    "Meizu Pro 6 Plus",
                    "Meizu M5",
                    "Meizu M2 mini",
                    "Meizu Pro 7 Plus",
                    "Meizu M6s",
                ],
            ],
            "msi" => [
                "n" => [
                    "MSI gp72 2qe leopard pro",
                    "MSI gx60 6qd",
                    "MSI ge62 2qc apache",
                    "MSI gl72 6qc",
                    "MSI px60 2qd",
                    "MSI px60 6qe",
                    "MSI pe60 2qd",
                    "MSI pe60 2qe",
                    "MSI pe60 6qd",
                    "MSI pe60 6qe",
                    "MSI pe70 2qd",
                    "MSI pe70 2qe",
                    "MSI pe70 6qd",
                    "MSI pe70 6qe",
                    "MSI s20",
                    "MSI s20 slider 2",
                ],
            ],
            "samsung" => [
                "p" => [
                    "Samsung Galaxy Tab Active 8.0",
                    "Samsung Galaxy Tab 3 10.1",
                    "Samsung Galaxy Tab E 9.6",
                    "Samsung Galaxy Tab 3 8.0",
                    "Samsung Galaxy Note 10.1",
                    "Samsung Galaxy Tab 10.1",
                    "Samsung Galaxy Tab S3 9.7",
                    "Samsung Galaxy Tab A 10.1",
                    "Samsung Galaxy Tab A 7.0",
                    "Samsung Galaxy Tab S2 8.0 S2",
                    "Samsung Galaxy Tab",
                ],
                "f" => [
                    "Samsung Galaxy S3 Neo",
                    "Samsung Galaxy Note 5",
                    "Samsung Galaxy S5",
                    "Samsung Galaxy Alpha",
                    "Samsung Galaxy J1",
                    "Samsung Galaxy S5 mini",
                    "Samsung Galaxy Grand Prime VE Duos",
                    "Samsung Galaxy J5 Prime",
                    "Samsung Galaxy A3",
                    "Samsung Galaxy A8",
                    "Samsung Galaxy Note 4",
                    "Samsung Galaxy S6 edge",
                    "Samsung Galaxy J3",
                    "Samsung Galaxy Note 8",
                    "Samsung Galaxy S8 Plus",
                    "Samsung Galaxy J5",
                    "Samsung Galaxy A7",
                    "Samsung Galaxy A5",
                    "Samsung Galaxy S9 Plus",
                    "Samsung Galaxy S9",
                    "Samsung Galaxy S III",
                    "Samsung Galaxy E5",
                    "Samsung Galaxy J1 mini Prime",
                    "Samsung Galaxy J7",
                    "Samsung Galaxy Core 2 Duos",
                    "Samsung Galaxy Grand Prime",
                    "Samsung Galaxy S6",
                    "Samsung Galaxy S7",
                    "Samsung Galaxy S4 Mini Duos",
                    "Samsung Galaxy S8",
                    "Samsung J2",
                    "Samsung Galaxy S7 Edge",
                    "Samsung Galaxy A6 2018",
                    "Samsung Galaxy A6 Plus 2018",
                ],
                "n" => [
                    "Samsung NP300E5C",
                    "Samsung R540",
                    "Samsung RV511",
                    "Samsung NP300E7A",
                    "Samsung NP R425",
                    "Samsung RC530",
                    "Samsung 305V5A",
                    "Samsung NP300E5A",
                    "Samsung N150",
                    "Samsung NP305E5A",
                    "Samsung R430",
                    "Samsung NP355V5C",
                    "Samsung R525",
                    "Samsung NP350V5C",
                    "Samsung RV515",
                    "Samsung RV520",
                    "Samsung NP370R5E",
                    "Samsung NP530U3C",
                    "Samsung NP RV515",
                    "Samsung NP-NC110",
                ],
            ],
            "sony" => [
                "n" => [
                    "Sony vaio vpc-eh",
                    "Sony vaio fit e svf1521f1r",
                    "Sony vaio vgn-sr11mr",
                    "Sony vaio vgn-ns21sr",
                    "Sony vaio sve",
                    "Sony vaio vgn-g",
                    "Sony vaio vgn-p21zr",
                    "Sony vaio vgn-s4hrp",
                    "Sony vaio vgn-ux1xrn",
                    "Sony vaio vpcea1s1r",
                    "Sony vaio vpcef3e1r",
                    "Sony vaio vpcsb1v9r",
                ],
                "p" => [
                    "Sony xperia tablet s",
                    "Sony xperia tablet z",
                    "Sony xperia tablet z2",
                    "Sony xperia tablet z3 mini",
                    "Sony xperia tablet z4",
                ],
                "f" => [
                    "Sony X/X Dual( f5121/5122)",
                    "Sony XA/XA dual(а3111/3121)",
                    "Sony X Comp f5321",
                    "Sony XA Ultra F3212",
                    "Sony Z Ultra C6833",
                    "Sony XA2 Ultra",
                    "Sony XZ1",
                    "Sony XZ",
                    "Sony XZs",
                    "Sony XA2",
                    "Sony XA1",
                    "Sony XZ1 Compact",
                    "Sony XZ2 Compact",
                    "Sony XZ Premium",
                    "Sony XZ2 H8296",
                    "Sony T2 Ultra",
                    "Sony M4 Aqua e2303",
                    "Sony Xperia J st26i",
                    "Sony Xperia E3 d2202",
                    "Sony M2 d2305",
                    "Sony Z1 Comp d5503",
                    "Sony T3 d5103",
                    "Sony Z3 Comp d5803",
                    "Sony XA1 Ultra G3221",
                    "Sony Xperia E4g",
                    "Sony Xperia L1 G3312",
                    "Sony Xperia M5 Dual E5603",
                    "Sony Xperia Z3 D6603",
                    "Sony Xperia Z5",
                    "Sony Xperia Z5 Premium",
                    "Sony Xperia Z3+",
                    "Sony Xperia C5 Ultra Dual",
                    "Sony Xperia Z2",
                    "Sony Xperia C4",
                    "Sony Xperia X Performance",
                    "Sony Xperia L2",
                    "Sony Xperia Z5 Compact",
                    "Sony Xperia E5",
                    "Sony Xperia XA1 Plus Dual",
                ],
            ],
            "toshiba" => [
                "n" => [
                    "Toshiba satellite a300-15e",
                    "Toshiba satellite a300-15d",
                    "Toshiba satellite l50d-a-k1k",
                    "Toshiba satellite a660-158",
                    "Toshiba satellite c660-1fl",
                    "Toshiba qosmio x70-a-k2s",
                    "Toshiba satellite l350-107",
                    "Toshiba satellite l650d-120",
                    "Toshiba satellite c660-28k",
                    "Toshiba satellite l40-14b",
                    "Toshiba satellite l500-1un",
                    "Toshiba satellite l850-b5k",
                    "Toshiba satellite l855-d1m",
                    "Toshiba satellite p300-135",
                    "Toshiba satellite c660-15k",
                    "Toshiba satellite c660-168",
                    "Toshiba satellite c850-e3w",
                    "Toshiba satellite c870-b3w",
                    "Toshiba satellite c870-dmk",
                    "Toshiba satellite c870-dqk",
                    "Toshiba WT310-108",
                    "Toshiba Encore",
                    "Toshiba Satellite Click mini",
                    "Toshiba AT300-105",
                    "Toshiba Excite Write",
                ],
            ],
            "zte" => [
                "f" => [
                    "ZTE blade v8",
                    "ZTE blade a6",
                    "ZTE blade a510",
                    "ZTE blade v7",
                    "ZTE blade a5",
                    "ZTE blade x3",
                    "ZTE blade a610",
                    "ZTE blade v9",
                    "ZTE blade pro",
                    "ZTE nubia z11",
                    "ZTE blade l5",
                    "ZTE nubia z17",
                    "ZTE blade lux",
                    "ZTE blade 3",
                    "ZTE nubia z11 mini",
                    "ZTE nubia mini s",
                    "ZTE nubia n1",
                    "ZTE nubia m2 lite",
                    "ZTE nubia z11 max",
                    "ZTE nubia z9 mini",
                ],
            ],
            "oneplus" => [
                "f" => [
                    "OnePlus One",
                    "OnePlus 2",
                    "OnePlus 3",
                    "OnePlus 3T",
                    "OnePlus 5",
                    "OnePlus 5T",
                    "OnePlus 6",
                ],
            ],
            "nokia" => [
                "f" => [
                    "Nokia 2 Duai Sim",
                    "Nokia Lumia 1320",
                    "Nokia 3 Dual Sim",
                    "Nokia Lumia 1520",
                    "Nokia 5 Dual Sim",
                    "Nokia Lumia 930",
                    "Nokia 6",
                    "Nokia Lumia 1020",
                    "Nokia 6.1",
                    "Nokia 7 Plus Dual",
                    "Nokia 8 Dual Sim",
                    "Nokia 8 Sirocco Dual Sim",
                ],
            ],
            "leeco" => [
                "f" => [
                    "LeEco Le 2 X 527",
                    "LeEco Le Max 2",
                    "LeEco Le 2 Pro",
                ],
            ],

        ];

        return $populars;
    }
}
if (!function_exists('get_popular')) {
    function get_popular($site_id, $marka_lower, $feed)
{    
    $merge_popular = [];
    $populars = get_populars();
    
    $sql = "SELECT `models`.`id` as `id`, `models`.`name` as `name`, `model_types`.`name` as `model_type_name` FROM `model_to_sites`
                INNER JOIN `models` ON `models`.`id`=`model_to_sites`.`model_id`
                    INNER JOIN `m_models` ON `m_models`.`id`=`models`.`m_model_id`
                        INNER JOIN `model_types` ON `m_models`.`model_type_id`=`model_types`.`id`
                            WHERE `model_to_sites`.`site_id`=:site_id";
    
    $stm = pdo::getPdo()->prepare($sql);
    $stm->execute(array('site_id' => $site_id));
    $data = $stm->fetchAll(\PDO::FETCH_ASSOC);
    
    $exclude = get_exclude();
     
    foreach ($data as $key => $value)
        if (in_array($value['id'], $exclude)) unset($data[$key]);     
    
    if (isset($populars[$marka_lower]))
    {
        $popular_in_site = $populars[$marka_lower];
        
        $t = [];
        foreach ($data as $value)
        {
            $suffics = tools::get_suffics($value['model_type_name']);
            $t[$suffics][mb_strtolower($value['name'])] = ['id' => $value['id'], 'name' => $value['name'], 'suffics' => $suffics];       
        }
      
        foreach ($popular_in_site as $suffics => $array)
        {
            foreach ($array as $val)
            {
                $val = mb_strtolower($val);
                if (isset($t[$suffics][$val])) $merge_popular[] = $t[$suffics][$val];
            }
        }
        
        if ($merge_popular)
        {
            $count_m = floor(count($merge_popular) / 4) * 4;
            if ($count_m > 24) $count_m = 24;        
            $merge_popular = rand_it::randMas($merge_popular, $count_m, '', $feed);
        }
    }
    
    return $merge_popular;
}
}
