<?php
$file = "Disallow: /wp-includes/
Disallow: /discount/
Disallow: /wp-admin/
Disallow: /wp-content/plugins/
Disallow: /wp-content/cache/
Disallow: /wp-content/themes/
Disallow: /wp-comments
Disallow: /xmlrpc.php
Disallow: /author/
Disallow: /page/
Disallow: */feed
Disallow: */trackback
Disallow: */comments
Disallow: /*?*
Disallow: /*.php
Disallow: /index.php
Disallow: /test.php
Disallow: /otzyvy/
Disallow: /otpravleno/
Allow: */#marka-*/$
#close
Disallow: */#marka-*/batareya
Disallow: */#marka-*/camera
Disallow: */#marka-*/gnezdo-pitaniya
Disallow: */#marka-*/hdd-ssd
Disallow: */#marka-*/keypad
Disallow: */#marka-*/kontroller
Disallow: */#marka-*/matritsa-ekrana
Disallow: */#marka-*/microfon
Disallow: */#marka-*/ne-vidit-microfon
Disallow: */#marka-*/ne-vidit-usb
Disallow: */#marka-*/ne-vklyuchaetsya-kamera
Disallow: */#marka-*/ozu
Disallow: */#marka-*/plata
Disallow: */#marka-*/polosi-na-monitore
Disallow: */#marka-*/postoyanno-perezagruzhaetsya
Disallow: */#marka-*/razborka
Disallow: */#marka-*/razyom-hdmi
Disallow: */#marka-*/razyom-usb
Disallow: */#marka-*/remont-hdd
Disallow: */#marka-*/remont-hdmi
Disallow: */#marka-*/remont-kamery
Disallow: */#marka-*/remont-kontrollera
Disallow: */#marka-*/remont-kulera
Disallow: */#marka-*/remont-microfona
Disallow: */#marka-*/remont-platy
Disallow: */#marka-*/remont-razyoma-pitaniya
Disallow: */#marka-*/remont-shleyfa
Disallow: */#marka-*/remont-tac#markaada
Disallow: */#marka-*/remont-usb
Disallow: */#marka-*/remont-videokarty
Disallow: */#marka-*/remont-zvukovoy-karty
Disallow: */#marka-*/sam-vyklyuchaetsya
Disallow: */#marka-*/sevenyy-most
Disallow: */#marka-*/shleyf
Disallow: */#marka-*/tach
Disallow: */#marka-*/ventilyator
Disallow: */#marka-*/video-karta
Disallow: */#marka-*/vosstanovlenie-tsepi-pitaniya
Disallow: */#marka-*/wifi-modul
Disallow: */#marka-*/yuzhnyy-most
Disallow: */#marka-*/zamena-ozu
Disallow: */#marka-*/zamena-severnogo-mosta
Disallow: */#marka-*/zamena-yuzhnogo-mosta
Disallow: */#marka-*/zamena-zu
Disallow: */#marka-*/zaryadka
Disallow: */#marka-*/zvukovaya-plata
Disallow: */#marka-*/derzhatel-sim
Disallow: */#marka-*/dinamic
Disallow: */#marka-*/ekran
Disallow: */#marka-*/gps-modul
Disallow: */#marka-*/knopka
Disallow: */#marka-*/ne-nazhimaetsya-knopka
Disallow: */#marka-*/ne-opredelyaetsya-simkarta
Disallow: */#marka-*/ne-rabotaet-ekran
Disallow: */#marka-*/ne-rabotaet-microfon
Disallow: */#marka-*/ne-rabotaet-vibratsiya
Disallow: */#marka-*/ne-vidit-wifi
Disallow: */#marka-*/remont-dinamika
Disallow: */#marka-*/remont-gps
Disallow: */#marka-*/remont-knopki
Disallow: */#marka-*/remont-korpusa
Disallow: */#marka-*/remont-kryshki
Disallow: */#marka-*/remont-simholdera
Disallow: */#marka-*/remont-vibro
Disallow: */#marka-*/tresnula-kryshka
Disallow: */#marka-*/vibromotor
Disallow: */#marka-*/zadnyaya-kryshka
Disallow: */#marka-*/zaschitniy-korpus
Disallow: */#marka-*/ne-vklyuchaetsya-gps
Disallow: */#marka-*/shleyf-platy
Disallow: */#marka-*/ne-vklyuchaetsya
Disallow: */#marka-*/perestal-zaryazhatsya
Disallow: */#marka-*/remont-klaviatury
Disallow: */#marka-*/remont-matritsy
Disallow: */#marka-*/zamena-akkumulyatora
Disallow: */#marka-*/zamena-ekrana
Disallow: */#marka-*/greetsya
Disallow: */#marka-*/remont-wifi
Disallow: */#marka-*/tresnul-ekran
Disallow: */#marka-*/ne-opredelyaet-tac#markaad
Disallow: */#marka-*/ne-pechataet-klaviatura
Disallow: */#marka-*/ne-podklyuchaetsya-wifi
Disallow: */#marka-*/silno-shumit
Disallow: */#marka-*/sinii-ekran
Disallow: */#marka-*/bystro-razryazhaetsya
Disallow: */#marka-*/chistka
Disallow: */#marka-*/diagnostics
Disallow: */#marka-*/nastroika-bios
Disallow: */#marka-*/nastroika-draiverov
Disallow: */#marka-*/nastroika-os-windows
Disallow: */#marka-*/ne-gorit-ekran
Disallow: */#marka-*/ne-rabotaet-hdd
Disallow: */#marka-*/ne-vidit-hdmi
Disallow: */#marka-*/feed
Disallow: */#marka-*/slomalsya-korpus
Disallow: */#marka-*/ne-rabotaet-zvuk
Disallow: */#marka-*/ne-zapuskaetsya
Disallow: */#marka-*/ne-reagiruet-tachskrin
Disallow: */#marka-*/propal-zvuk";?>