Disallow: /wp-includes/
Disallow: /discount/
Disallow: /wp-admin/
Disallow: /wp-content/plugins/
Disallow: /wp-content/cache/
Disallow: /wp-content/themes/
Disallow: /wp-comments
Disallow: /xmlrpc.php
Disallow: /author/
Disallow: /page/
Disallow: */feed
Disallow: */trackback
Disallow: */comments
Disallow: /*?*
Disallow: /*.php
Disallow: /index.php
Disallow: /test.php
Disallow: /otzyvy/
Disallow: /otpravleno/